spring.application.name=catalogo-service
server.port=8082
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.max-http-request-header-size=16KB
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=BuganvillaCatalogo;encrypt=true;trustServerCertificate=true;}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

jwt.secret=${JWT_SECRET:mySuperSecretKeyForBuganvillaToursApplication2024SecurityWithSpringBoot3}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000,http://localhost:8080}
logging.level.com.backend.catalogo_service=${LOG_LEVEL:INFO}
